### ISSUE TITLE
only merge/unmerge functionality and making it work alongside the built-in table module

### ISSUE THREAD

**Issue by fjrial** [soccerloway/quill-better-table#22]
Just asking, 

Due to the latest development in QuillJS, table support is built-in in the latest 2.0.0 versions. Sure you know that.

I want to use the built-in functionality (in fact I've already developed the menus with all options to manage tables,rows,columns inside the toolbar and using the already provided table module), but I'm missing the merge/unmerge options.

Do you think it's possible to compile your library but only using the merge/unmerge module and make it work alongside the built-in functionality for tables (without disabling the current table module) ??

Other approach I'm following is trying to make my own selector for cells: currently I can select several cells like you do in your module, but the events I've attached to the td elements do not allow me to select the text inside the cell.. I'm reading your code to try to understand how do you do this part.. working on it.

Thank you for your wonderful module!!! and for any advice you can give me.

**Comment by fjrial** [comment]
Other option I'm considering is integrating your module (disabling the built-in one), and use its functionality under my already created toolbar menu for tables.

**Comment by fjrial** [comment]
finally I did it using the last option.. seems the easiest to implement.

integrating your module, disabling the visualization of the contextual menu, and using my own buttons in the toolbar.

**Comment by soccerloway** [comment]
I apology for the delay. 
I found my module was hard to use in your case since I haven't exposed the merge/unmerge apis on my modules. To implement that, I think you would use your custom buttons in the toolbar, and attach the handlers like [the document of Quill toolbar module](https://quilljs.com/docs/modules/toolbar/). You can access `tableSelection` via `tableModule`, and call `mergeCells/unmergeCells` via `TableContainer` blot.
Fortunately, you finally implement it:)

**Comment by fjrial** [comment]
please, don't need to apology, thanks to you for your nice module and also for giving me advice.
