### ISSUE TITLE
Copying and pasting individual H1 tags will not work

### ISSUE THREAD

**Issue by kagol** [soccerloway/quill-better-table#30]
Copying and pasting individual H1 tags will not work, but when the H1 tag is copied and pasted with other tags, it is really good.
This problem only appeared in Quill 2.0.0-dev.x, Quill 1.3.6 does not have this problem.

**Comment by soccerloway** [comment]
It's really a problem in Quill 2.0.0-dev.x. 
We better create an issue in quillJs official repo~
Maybe a PR~

**Comment by soccerloway** [comment]
I found it caused by the code in quilljs:
![image](https://user-images.githubusercontent.com/8068440/69841664-15037380-129b-11ea-9580-dd68e33a19f8.png)
`getHTML` is called in `onCopy`, and the return html will be cached in clipboard.
It looks like the author handles inline copying and multi-line copying separately, I haven't figured out what the purpose was.
If I remove the `if` logic statement, copying and pasting individual h1 tag will work.

**Comment by soccerloway** [comment]
I have already create a new issue about this in quilljs repo.
[Copying and pasting individual H1 tags will not work](https://github.com/quilljs/quill/issues/2853),
We could dicuss this problem there~

**Comment by kagol** [comment]
Thank you for your timely response and suggestion, which is very helpful to me.
