### ISSUE TITLE
Could you document what the Delta format looks like?

### ISSUE THREAD

**Issue by npcole** [soccerloway/quill-better-table#6]
What do Delta's look like for these tables? How does it differ from the 'official' Quilljs Delta format 2.0 for tables?

**Comment by soccerloway** [comment]
![image](https://user-images.githubusercontent.com/8068440/58391419-76d2ee80-8068-11e9-9a8f-5784e99d7b0f.png)
Hi, @npcole 
`quill-better-table` has some conflict with the official table module, so you need to disabled the official table module in editor initialize.

**Comment by soccerloway** [comment]
About the Delta format,
![image](https://user-images.githubusercontent.com/8068440/58393085-9b7e9480-806f-11e9-85d9-bebb7d991077.png)

**Comment by soccerloway** [comment]
![image](https://user-images.githubusercontent.com/8068440/58393203-3d9e7c80-8070-11e9-98a5-5c6ad8e05dd6.png)
quill-delta structure is flat, the data structure between red lines correspond to a `col` html tag, every `col` will be wrapped with a `colgroup` tag. `colgroup` tags will be merged in blot's `optimize` phase.
Since the `checkMerge` api of `TableColGroup` always return `true`, the `colgroup` tags will be mreged into only one `colgroup` tag.

**Comment by soccerloway** [comment]
![image](https://user-images.githubusercontent.com/8068440/58394320-362da200-8075-11e9-90fb-c9e494f86f30.png)
In the delta of table, `{ insert: '\n' }` means that it is a block blot.
`{ insert: '\n', attributes: { table-cell-line: { object } } }` means that the bock blot is a instance of TableCellLine blot, and the **object** is attributes of TableCellLine.

**Comment by soccerloway** [comment]
@npcole I am not sure if it will help you ?

**Comment by soccerloway** [comment]
I will close this issue~
